version: "2"

services:

  selenium:
    image: eeacms/emrt.necd.test:latest
    cap_add:
      - ALL
    depends_on:
      - plone
    env_file:
      - ./selenium.env
    command: "/run.sh"

  plone:
    image: eeacms/plone-emrt-necd:staging
    environment:
      ZOPE_MODE: "standalone"

  memcached:
    image: memcached:1.4.37
    command:
      - -m
      - '2048'
