version: "2"
services:
  selenium:
    build: .
    cap_add:
      - ALL
    depends_on:
      - plone
    env_file:
      - ./selenium.env
    command: "bash -c 'bash -c \"$$COMMAND\"'"
    
  plone:
    image: eeacms/plone-emrt-necd:staging
    environment:
      ZOPE_MODE: "standalone"

  memcached:
    image: memcached:1.4.37
    command:
    - -m
    - '2048'
